### ISSUE TITLE
Getting an error when attempting to unpack data.wak

### ISSUE THREAD

**Issue by remghoost** [isJuhn/UnWak#1]
Hello. I know this repo is three years old but I figured I'd submit an issue before I dove into cryptography and tried to figure out how your program works.

I'm fairly certain I'm running your program correctly (I've tried it in an external folder and dropped directly into the noita/data folder), and I have tried both building it myself and running the prebuilt exe from the releases tab.

Though sometimes I am indeed not smart, so it may still be a user based error.
But running `unwak data.wak` seems fairly hard to mess up.

-----------

Here's the error I'm getting

`Unhandled exception. System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.`

`at UnWak.WakDecryptor.DecryptWak(Byte[] wak_file, Byte[] output) in C:\git\UnWak\UnWak\WakDecryptor.cs:line 28`

`at UnWak.Program.Main(String[] args) in C:\git\UnWak\UnWak\Program.cs:line 24`

------------
Here are the alleged lines of code.

https://github.com/isJuhn/UnWak/blob/65508a108a7eab58b626a10fcbb158ad32c073d1/UnWak/WakDecryptor.cs#L26-L32

https://github.com/isJuhn/UnWak/blob/65508a108a7eab58b626a10fcbb158ad32c073d1/UnWak/Program.cs#L19-L26

----------

I'm guessing your program was just for an earlier build of Noita and some things have changed around since then.

Anyways, if you're bored and want to fix it, that'd be awesome.
I'll more than likely be poking around to see if I can fix it myself.

**Comment by isJuhn** [comment]
I'm fairly sure they removed the encryption after a while and this program is now useless. But I can check it tomorrow or something. If the files are still encrypted but with a new format I might update this, but I doubt it.

**Comment by remghoost** [comment]
I may be misunderstanding the point of the program then.....

When opened with something like notepad++, the code in the wak file is mostly readable. 
I figured your program "unpacked" it. 

I've seen references to files like `data/entities/projectiles/thunderball.xml`, which don't exist in the Noita directory or `\AppData\LocalLow\Nolla_Games_Noita`.
I assumed that the wak file was a compressed "zip" of sorts with the rest of those assets.

**Comment by isJuhn** [comment]
It used to be an encrypted archive, so the point of the program was to decrypt it and unpack it. If they removed the encryption as I suspect, it only needs to be unpacked and my program will try to decrypt and already decrypted archive and thus crash.

**Comment by remghoost** [comment]
Ah! That checks out.

I have also learned as of five minutes ago that there is an unpacking tool in the `tools_modding` folder.
It seems to have been a user error all along. haha.

My apologies for necro-ing a three year old repo.
Have a good day!
